version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx-server
      dockerfile: cert.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mateusz.malecki@digimonkeys.com -d digimonkeys-speech2txt.com --agree-tos