version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: speech-to-text
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: ./app
    command: bash -c "wait-for-it --service db:5432 && alembic upgrade head && python run.py"
    tty: True
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    logging:
      driver: none

  signaling_server:
    container_name: signaling_server
    build: ./signaling_server
    tty: True
    command: bash -c "python server.py"
    volumes:
      - ./signaling_server:/signaling_server
    ports:
      - "9000:9000"

volumes:
  db_data:
  pgadmin_data: