version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: speech-to-text
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    logging:
      driver: none

  app:
    container_name: app
    build: ./app
    command: bash -c "wait-for-it --service db:5432 --timeout 30 && alembic upgrade head && python main.py"
    tty: True
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"

  socket_server:
    container_name: socket_server
    build: ./socket_server
    tty: True
    command: bash -c "python server.py"
    volumes:
      - ./socket_server:/socket_server
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx-server
      dockerfile: prod.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-server/dist:/html/front
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  db_data: