"""6_add_room_table

Revision ID: 131bf2d40dac
Revises: e9ee772e9778
Create Date: 2023-01-25 14:49:29.249523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131bf2d40dac'
down_revision = 'e9ee772e9778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room_user_association_table',
    sa.Column('room_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('recording', sa.Column('room_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'recording', 'room', ['room_name'], ['name'], ondelete='CASCADE')
    op.add_column('transcription', sa.Column('room_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transcription', 'room', ['room_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcription', type_='foreignkey')
    op.drop_column('transcription', 'room_name')
    op.drop_constraint(None, 'recording', type_='foreignkey')
    op.drop_column('recording', 'room_name')
    op.drop_table('room_user_association_table')
    op.drop_table('room')
    # ### end Alembic commands ###
