"""2_filenames

Revision ID: 1db958c2358b
Revises: 70883d2283b0
Create Date: 2022-12-07 13:36:57.779274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db958c2358b'
down_revision = '70883d2283b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recording', sa.Column('filename', sa.String(length=256), nullable=False))
    op.alter_column('recording', 'url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.add_column('transcription', sa.Column('filename', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription', 'filename')
    op.alter_column('recording', 'url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('recording', 'filename')
    # ### end Alembic commands ###
