"""1_init

Revision ID: 70883d2283b0
Revises: 
Create Date: 2022-12-06 12:25:21.746952

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from auth.hash import Hash


# revision identifiers, used by Alembic.
revision = '70883d2283b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duration', sa.Float(precision=2), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('reset_code', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    users_table = op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        users_table,
        [
            {
                "email": "admin@admin.com",
                "password": Hash.get_password_hash("admin"),
                "name": "Admin"
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription')
    op.drop_table('user')
    op.drop_table('reset_password')
    op.drop_table('recording')
    # ### end Alembic commands ###
