"""3_chnges_in_relationships

Revision ID: 7d3799b904c6
Revises: 1db958c2358b
Create Date: 2022-12-07 13:57:42.602978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3799b904c6'
down_revision = '1db958c2358b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
