"""5_remove_relations

Revision ID: e9ee772e9778
Revises: fc68c53d3937
Create Date: 2023-01-20 10:56:05.563327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ee772e9778'
down_revision = 'fc68c53d3937'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transcription_recording_id_fkey', 'transcription', type_='foreignkey')
    op.drop_column('transcription', 'recording_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transcription_recording_id_fkey', 'transcription', 'recording', ['recording_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
