"""4_add_transcription_url

Revision ID: fc68c53d3937
Revises: 7d3799b904c6
Create Date: 2023-01-03 09:57:33.414405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc68c53d3937'
down_revision = '7d3799b904c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('url', sa.String(length=256), nullable=False))
    op.drop_column('transcription', 'transcription_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('transcription_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('transcription', 'url')
    # ### end Alembic commands ###
