name: Deploy frontend

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'frontend/**'

defaults:
  run:
    shell: bash

env:
  PROJECT_ID: complete-road-374207
  GCE_INSTANCE_NAME: speech2txt
  GCE_INSTANCE_ZONE: europe-west3-c

jobs:
  deploy-frontend:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Pull changes
        run: |
          gcloud compute ssh --project ${{ env.PROJECT_ID }} --zone ${{ env.GCE_INSTANCE_ZONE }} ${{ env.GCE_INSTANCE_NAME }} --command="ls && git pull"

      - name: Build
        run: |
          gcloud compute ssh --project ${{ env.PROJECT_ID }} --zone ${{ env.GCE_INSTANCE_ZONE }} ${{ env.GCE_INSTANCE_NAME }} --command="ls && sudo npm install && sudo npm run build"

      - name: Move new build to nginx
        run: |
          gcloud compute ssh --project ${{ env.PROJECT_ID }} --zone ${{ env.GCE_INSTANCE_ZONE }} ${{ env.GCE_INSTANCE_NAME }} --command="ls && sudo mv frontend/dist nginx-server/dist"
